export {default as Meta} from '@/components/top/meta'
export {default as Header} from '@/components/top/header'
export {default as Footer} from '@/components/top/footer'
export {default as CheckoutForm} from '@/components/top/checkoutForm'
export {default as Make} from '@/components/top/make'
export {default as Faq} from '@/components/top/faq'
export {default as Move} from '@/components/top/move'
export {default as Plan} from '@/components/top/plan'